# Generated by Django 2.1.5 on 2020-12-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
