# Generated by Django 2.1.5 on 2020-12-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
