# Generated by Django 3.1.3 on 2020-12-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customize',
            new_name='About',
        ),
    ]
